# Generated by Django 4.0.3 on 2022-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0002_keycap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Switches',
        ),
    ]
