# Generated by Django 4.0.3 on 2022-05-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0004_switche_description_alter_switche_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='switche',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keyboard.keyboard'),
        ),
    ]
