# Generated by Django 4.0.3 on 2022-05-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0005_switche_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='switche',
            name='keycap',
            field=models.ManyToManyField(null=True, to='keyboard.keycap'),
        ),
    ]
