# Generated by Django 4.0.3 on 2022-05-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0007_remove_switche_description_remove_switche_keycap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='keycap',
            field=models.ManyToManyField(to='keyboard.keycap'),
        ),
    ]
