# Generated by Django 4.0.3 on 2022-06-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0008_alter_keyboard_keycap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='description',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='size',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
